[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions_singleapp_large.csv
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_FREERTOS_HZ=1000
    -I include
